---

# this is just a sample configuration file.
# Fill in real data and rename it to app_secret.yml

development: &defaults
  facebook_app_id: "ACTUAL-ID-WOULD-GO-HERE"
  facebook_app_secret: "ACTUAL-SECRET-WOULD-GO-HERE"

production:
  <<: *defaults

test:
  <<: *defaults